---
title: Blog de Cehm
email: ---
description: |
  Site sur la bouffe, comment manger mieux. J'essais de donner des bons tips pour perdre du poids.
baseurl: ''
url: ''
twitter_username: ---
github_username: ---
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
timezone: Europe/Budapest
